name: Clone Repo Workflow

on:
  push:
  schedule:
    - cron: '56 15 * * *'
  workflow_dispatch:
    
jobs:
  job-public-repo-window:
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
         owner: 'thomasloven'
         repository: 'hass-config'
      - name: Access repo content
        run: |
          mkdir hass-config_data/data
          cp -v hass-config/appdaemon/apps/helpers/* hass-config_data/data
