name: Clone Repo Workflow

on:
  push:
  schedule:
    - cron: '36 15 * * *'
  workflow_dispatch:
    
jobs:
  job-public-repo-window:
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
         owner: 'thomasloven'
         repository: 'hass-config'
      - name: Access repo content
        run: |
          mv -v hass-config/appdaemon/apps/helpers/* hass-config/data
          rm -rf hass-config
          git checkout -b $(date "+%Y-%m-%d") 
          git commit -m "Updating RepoName data"
          git push origin $(date "+%Y-%m-%d")
