name: Clone Repo Workflow

on:
  push:
  schedule:
    - cron: '19 17 * * *'
  workflow_dispatch:
    
jobs:
  job-public-repo-window:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
         owner: 'thomasloven'
         repository: 'hass-config'
      - name: Access repo content
        run: |
          mkdir ~/hass-config_data/data
          cp -v hass-config/appdaemon/apps/helpers/* ~/hass-config_data/data/
          rm -rf hass-config
          git checkout -b $(date "+%Y-%m-%d")
          git add ./data
          git commit -m "Updating Hass Config data."
          git push origin $(date "+%Y-%m-%d")
